trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'mezzodevprojectacr'
  IMAGE_NAME: 'mezzodevprojectacr/myapp'
  RESOURCE_GROUP: 'mezzo-dev-resource-group'
  AKS_CLUSTER_NAME: 'mezzo-dev-aks-cluster'  # Your AKS cluster name
  IMAGE_TAG: 'latest'  # Image tag, usually 'latest'
  

steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'acrnew'

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: '$(ACR_NAME)/$(IMAGE_NAME)'
      dockerfile: 'Dockerfile'
      tags: '$(IMAGE_TAG)'
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'test1'
      command: 'apply'
      arguments: '-f k8s/deployment.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

  # Step 4: Deploy the Docker image to AKS using the service YAML file
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'test1'
      command: 'apply'
      arguments: '-f k8s/service.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

  # Step 5: Update the Deployment to use the latest image from ACR
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'test1'
      command: 'set'
      arguments: 'image deployment/myapp-deployment myapp=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

  # Step 6: Restart deployment to apply changes
  #- task: Kubernetes@1
  #  inputs:
  #    connectionType: 'Kubernetes Service Connection'
  #    kubernetesServiceEndpoint: 'test1'
  #    command: 'rollout'
  #    arguments: 'restart deployment/myapp-deployment'
  #   secretType: 'dockerRegistry'
  #    containerRegistryType: 'Azure Container Registry'